### ISSUE TITLE
configure-lfs-for-vivado

### ISSUE THREAD

**Issue by adamschoenwald** [ComPair/ComPair-tracker-FPGA#1]
Set up .gitattibutes to identify vivado binaries for LFS

**Comment by SeanCGriffin** [comment]
.gitattributes file now exists; repository using git-lfs; need to add the right Vivado file extensions now.

**Comment by adamschoenwald** [comment]
Add to readme:
To add all png files to lfs, run `git lfs track "*.png`
To see what is being tracked, run `git lfs ls-files`
Note:Always execute the "track" command from the root of your project.
