### ISSUE TITLE
Only some ASICS read out on REVA

### ISSUE THREAD

**Issue by adamschoenwald** [ComPair/ComPair-tracker-FPGA#131]
Attempt to keep track of work done to fix this issue

Firmware swap attempt:
s0, s1, s2, s_latch, i1, i3, i4, o5, o6 are all swapped for the
following asic pairs:
1, 4
2, 6
3, 11

Pre Swap:
ASIC's 0,1,2,3 are working.
ASIC's 4,5 can clock config, but data is all 0
ASIC's 6-11 (side B) are not clocking configs

Post Swap:
Configs working = 0, 1, 4, 5, 6, 11
Configs not working = 2,3,7,8,9,10
[post_swap_config_log.txt](https://github.com/ComPair/ComPair-tracker-FPGA/files/5624221/post_swap_config_log.txt)

**Comment by adamschoenwald** [comment]
Post Swap configuration register readout:
ASIC 0
----------------
Setting config; response:  ok
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 1
----------------
Setting config; response:  ok
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 2
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 3
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 4
----------------
Setting config; response:  ok
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 5
----------------
Setting config; response:  ok
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 6
----------------
Setting config; response:  ok
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 7
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 8
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 9
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 10
----------------
Setting config; response:  error: config_check
Setting up trigger configuration: 
	 syncctrl forced_readout triggers: ok
ASIC 11
----------------
Setting config; response:  ok
Setting up trigger configuration:

**Comment by adamschoenwald** [comment]
Prior to swap:
'''ASIC's 0,1,2,3 are working.
ASIC's 4,5 can clock config, but data is all 0
ASIC's 6-11 (side B) are not clocking configs.'''

**Comment by adamschoenwald** [comment]
Found the following problems in the schematics:
Schematic | actual
a6o5 - a7o6
a6o6 - a7o5
a7o5 - a6o6
a7o6 - a6o5

a8o5 - a9o6
a8o6 - a9o5
a9o5 - a8o6
a9o6 - a8o5

a10o5 - a11o6
a10o6 - a11o5
a11o5 - a10o6
a11o6 - a10o5

**Comment by SeanCGriffin** [comment]
This merge fixed the issue,
