### ISSUE TITLE
AFE 362/018 : O6 problems on some ASICS

### ISSUE THREAD

**Issue by adamschoenwald** [ComPair/ComPair-tracker-FPGA#148]

**Comment by SeanCGriffin** [comment]
ASIC Vthr_DAC = 1 for these tests. Readout is disabled so should just be looking at triggers. 

AFE S/N 362/008: 
With probe: No trigger data on A5-06; data on A3-O6 but intermittent and not always in the same place (i.e noisy trigger??). Confirmed with scope that A5-06 has data during readout. 

![image](https://user-images.githubusercontent.com/6585975/106326143-fe173300-6249-11eb-90fa-8384ca271b86.png)
![image](https://user-images.githubusercontent.com/6585975/106326343-50f0ea80-624a-11eb-88e8-a6893785e48e.png)

**Comment by SeanCGriffin** [comment]
AFE S/N 362/018:
With probe: Triggers on all ASICs; A5-06 is a BIT noisy.

Cranked threshold way up (31); see data on ALL channels during forced readout. 

Data not seen in web interface. 

![image](https://user-images.githubusercontent.com/6585975/106328378-b5617900-624d-11eb-95cc-8cba3308b78f.png)

**Comment by SeanCGriffin** [comment]
Finally, AFE 362/018: A4, A5 do not show triggers in ILA when pulse is sent. 

Recall, in live display, 2 ASICs are missing data. I have swapped AFEs before and watched the missing data go to A4,A5 on Side A; I think there's a mapping issue somewhere in raw2hdf. 

![image](https://user-images.githubusercontent.com/6585975/106328694-4173a080-624e-11eb-986e-4151104a43dc.png)

Pulse was checked at attenuator input on scope; pulses visible for these ASICs.

**Comment by adamschoenwald** [comment]
![a4a5_o6_zoomout](https://user-images.githubusercontent.com/6669107/107403939-b4dda380-6ad3-11eb-9c3c-b5b99b3f7131.png)
![a4a5_o6_closeup](https://user-images.githubusercontent.com/6669107/107403945-b60ed080-6ad3-11eb-9e24-7c7ae66aa10e.png)

**Comment by SeanCGriffin** [comment]
![image](https://user-images.githubusercontent.com/6585975/107811751-aa721280-6d3c-11eb-9e27-2b209593f245.png)

IC looks good. No shorts visible.

**Comment by SeanCGriffin** [comment]
![image](https://user-images.githubusercontent.com/6585975/107824496-92f05500-6d4f-11eb-9d97-4ddd60f64519.png)
![image](https://user-images.githubusercontent.com/6585975/107824502-95eb4580-6d4f-11eb-87a9-65298d3b508e.png)

LVDS transmitter lines are pegged to 2.7 V; inputs to transmitter looks OK. 


No shorts to ground; LVDS pins are open when disconnected from DBE, 100 Ohm when connected.

**Comment by SeanCGriffin** [comment]
Ken Simms eyeballed the chip, determined that Pin 1 wasn't soldered correctly. Data now present. Closing out the issue. 

![image](https://user-images.githubusercontent.com/6585975/109835101-e64c1980-7c10-11eb-8be2-923ec9423659.png)
![image](https://user-images.githubusercontent.com/6585975/109838493-38426e80-7c14-11eb-9984-170f3a1012ce.png)
