### ISSUE TITLE
Add SPI bus to MIO and try to integrate with linux modules

### ISSUE THREAD

**Issue by adamschoenwald** [ComPair/ComPair-tracker-FPGA#16]
Since the ADC and DAC have linux drivers, lets try to put these on the MIO SPI bus and then control over linux. Stretch goal = see if this works using the axi spi interface as well.

**Comment by lucasparker** [comment]
I tried to get the Zynq SPI working with the cal dac, but I was not successful. The SS lines did not behave as I wanted. With a single SPI driver instantiated on the Zynq, there are 3 select lines, and I did not see these lines changing at all. The select line for the interface I was writing to was always low, while the other lines remained high, so it seemed like it recognized which device I had configured to write to. 

In any case, this ended up with me mucking in petalinux with no idea what I was doing, and the SPI interface is simple enough that implementing it in firmware was easier for me.

I still have instructions for setting up the SPI interface here:
https://github.com/ComPair/ComPair-tracker-FPGA/wiki/petalinux-setup-notes#setup-spi-driver

We can keep this open though, as it would be nice if this could work.
