### ISSUE TITLE
Make abort_daq not static

### ISSUE THREAD

**Issue by lucasparker** [ComPair/ComPair-tracker-FPGA#21]
Currently there's a set timeout compiled in the firmware for the abort_daq signal (how long to wait before receiving trigger_ack before bailing on data readout/conversion). This should change to be read-in from an axi register, so that we can change it for testing purposes without re-compiling everything

**Comment by lucasparker** [comment]
This was done at some point. Timeout is now on the VATA axi register 20, goes by "trigger ack timeout"

**Comment by SeanCGriffin** [comment]
It's exciting when we (Lucas) closes out issues.
