### ISSUE TITLE
Reading livetime counters doesn't return the same value even when ASIC should be sleeping.

### ISSUE THREAD

**Issue by SeanCGriffin** [ComPair/ComPair-tracker-FPGA#43]
Probably related to the registers being read at slightly different times; we'll need to figure out how to correct for this.
![image](https://user-images.githubusercontent.com/6585975/75073221-fe01a580-54c6-11ea-8dd6-954385488aa1.png)

**Comment by lucasparker** [comment]
I am going to close this issue -- now the real-time and live-time counters are included in the asic data packets, and the values get latched at the same instant

**Comment by adamschoenwald** [comment]
Does the act of checking the counter stop the live counter?

**Comment by SeanCGriffin** [comment]
I believe that they are mapped to slv_regN's, so if they're free-running they shouldn't be affected by a read, since everything is synchronous to the AXI clk. Maybe @lucasparker can comment.
