### ISSUE TITLE
Enforcing data alignment when reading FIFO's

### ISSUE THREAD

**Issue by lucasparker** [ComPair/ComPair-tracker-FPGA#95]
Currently when the data-emitter process reads out asic packets from the vata fifo's, there are no checks done that the data being bundled together belongs to the same event.

There needs to be something added to the data-emitter to check the event id's of the asic packets, and do something to handle when the data coming out of the fifo's is not aligned

**Comment by SeanCGriffin** [comment]
@lucasparker We should have 10-12 ASIC data soon to test that the fix worked out and we can close this issue.

**Comment by SeanCGriffin** [comment]
This was fixed when data packet mailboxes were implemented on the Zynq.
